# Generated by Django 5.2.16 on 2026-07-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('banner', 'Banner principal'), ('comentario', 'Comentario / Resena'), ('video_tiktok', 'Video de TikTok'), ('galeria', 'Imagen de galeria')], max_length=30)),
                ('titulo', models.CharField(blank=True, max_length=150)),
                ('subtitulo', models.CharField(blank=True, max_length=200)),
                ('texto', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('texto_boton', models.CharField(blank=True, max_length=50)),
                ('url_boton', models.CharField(blank=True, max_length=200)),
                ('autor_nombre', models.CharField(blank=True, max_length=100)),
                ('autor_ubicacion', models.CharField(blank=True, max_length=100)),
                ('calificacion', models.PositiveSmallIntegerField(default=5)),
                ('etiqueta_producto', models.CharField(blank=True, max_length=100)),
                ('url_video', models.URLField(blank=True)),
                ('likes', models.CharField(blank=True, max_length=20)),
                ('reproducciones', models.CharField(blank=True, max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['tipo', 'orden'],
            },
        ),
    ]
