# Generated by Django 5.2.16 on 2026-07-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido_home', '0002_pregunta_quienessomos'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidohome',
            name='video_preview',
            field=models.FileField(blank=True, null=True, upload_to='home_videos/'),
        ),
    ]
