# Generated by Django 5.2.16 on 2026-07-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='costo_extra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='punto_recojo',
            field=models.CharField(blank=True, choices=[('plaza_puruchuco', 'Real Plaza Puruchuco'), ('mall_santa_anita', 'Mall Aventura Santa Anita'), ('plaza_norte', 'Plaza Norte'), ('megaplaza', 'Megaplaza')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='subtotal_productos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('shalom', 'Envio por Shalom'), ('contraentrega', 'Recojo - Contraentrega')], default='shalom', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
