# Generated by Django 5.2.16 on 2026-08-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_varianteproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoimagen',
            name='tipo',
            field=models.CharField(choices=[('galeria', 'Galería (fotos principales)'), ('detalle', 'Detalle (sección de abajo)')], default='galeria', max_length=20),
        ),
    ]
